//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TodoList
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class UICompletedListData : QFramework.UIPanelData
    {
        public TodoList Model = new TodoList();
    }

    public enum UICompletedListEvent {
        Start = UITodoListEvent.End,
        OnDataChanged,
        End,
    }

    public partial class UICompletedList : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            if (eventId == (int)UICompletedListEvent.OnDataChanged)
            {
                onDataChanged();
            }
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UICompletedListData ?? new UICompletedListData();
            // please add init code here
            onDataChanged();

            RegisterEvent(UICompletedListEvent.OnDataChanged);

            
        }

        protected override void RegisterUIEvent()
        {
            BtnBack.onClick.AddListener(() =>
            {
                CloseSelf();
                UIMgr.OpenPanel<UITodoList>(new UITodoListData() {
                    Model = mData.Model
                });
            });
        }

        void onDataChanged()
        {
            Content.DestroyAllChild();

            mData.Model.mTodoitem.Where(item => item.Completed).ForEach(item =>
            {
                UICompletedTodoitem.Instantiate()
                      .Parent(Content)
                      .LocalIdentity()
                      .ApplySelfTo((self) => self.Init(item))
                      .Show();
            });
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
