//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TodoList
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:d4bc5fe3-13bd-483a-929f-07607e7f81cc
    public partial class UICompletedList
    {
        
        public const string NAME = "UICompletedList";
        
        [SerializeField()]
        public UICompletedTodoitem UICompletedTodoitem;
        
        [SerializeField()]
        public UnityEngine.RectTransform Content;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        private UICompletedListData mPrivateData = null;
        
        public UICompletedListData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UICompletedListData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UICompletedTodoitem = null;
            Content = null;
            BtnBack = null;
            mData = null;
        }
    }
}
